name: notes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  music_notes: ^0.19.1
  riverpod: ^2.6.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
