name: notes
description: "A Musical Fluency App"
publish_to: 'none'
version: 0.1.5

environment:
  sdk: ^3.5.1

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_grid_button: ^2.1.0
  flutter_riverpod: ^2.6.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  material_symbols_icons: ^4.2800.2
  music_notes: ^0.19.1
  responsive_grid: ^2.4.4
  riverpod: ^2.6.1
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

